[package]
name = "FeOSMK1"
version = "0.1.0"
edition = "2024"
authors = ["Authors Harsh.shokka@gmail.com"]

[dependencies]
bootloader = "0.9.8"
volatile = "0.2.6"
spin = "0.5.2"
x86_64 = {version = "0.15.4", features = ["instructions"]}
uart_16550 = "0.6.0"
pic8259 = "0.10.1"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
#x86_64 = "0.14.2" # using the exit device 
# rather than using the In and Out assembly instructions 
# we create an abstraction provided by the x86_64 crate 
uart_16550 = "0.6.0"


[profile.dev]
panic = "abort" # disable stack unwinding on panic 

[profile.release]
panic = "abort" # disable stack unwinding on panic 

# double brackets means keys that can appear multiple times
[[bin]] # specifies how cargo should compile the executable 
name = "FeOSMK1"
test = true # do not build binary in test mode 
bench = false # do not build binary in bench mode 


# this is too be able to close the QEMU simulator and terminate the OS 
# without needing to do ctrl + C 
[package.metadata.bootimage]
test-args = [
    "-device", "isa-debug-exit,iobase=0xf4,iosize=0x04", "-serial", "stdio", 
    "-display", "none"
]
test-timeout = 300 # allowing our test to run for a maximum of 300 seconds (5 minutes )
test-success-exit-code = 33 # (0x10 << 1 | 1)
# isa-debug uses port mapped I/O
# iobase specifies which port address the device should live 
# iosize specifies the port size 
# iobase causes QEMU to exit with an exit status using this 
# logic (value << 1 | 1) where we shift the binary value 1 or 0 left 
# by 1 and then or'd by 1 

[[test]]
name = "should_panic"
harness = false

[[test]]
name = "stack_overflow"
harness = false
